
#!/bin/bash
# Get the directory where the script is located
WORKDIR=$(dirname "$0")

# Convert WORKDIR to a Windows-compatible path, if needed (for use with Git Bash)
WORKDIR=$(realpath "$WORKDIR")

# Define the list of all .cpp and .h files in the src directory
FILES_TO_UPDATE=(
    "$WORKDIR/src/addrman.cpp"
    "$WORKDIR/src/addrman.h"
    "$WORKDIR/src/alert.cpp"
    "$WORKDIR/src/alert.h"
    "$WORKDIR/src/allocators.h"
    "$WORKDIR/src/arith_uint256.h"
    "$WORKDIR/src/base58.h"
    "$WORKDIR/src/bignum.h"
    "$WORKDIR/src/bitcoinrpc.cpp"
    "$WORKDIR/src/bitcoinrpc.h"
    "$WORKDIR/src/chainparams.cpp"
    "$WORKDIR/src/chainparams.h"
    "$WORKDIR/src/chainparamsseeds.h"
    "$WORKDIR/src/checkpoints-orig.cpp"
    "$WORKDIR/src/checkpoints.cpp"
    "$WORKDIR/src/checkpoints.h"
    "$WORKDIR/src/clientversion.h"
    "$WORKDIR/src/coincontrol.h"
    "$WORKDIR/src/compat.h"
    "$WORKDIR/src/core.cpp"
    "$WORKDIR/src/core.h"
    "$WORKDIR/src/crypter.cpp"
    "$WORKDIR/src/crypter.h"
    "$WORKDIR/src/db.cpp"
    "$WORKDIR/src/db.h"
    "$WORKDIR/src/hash.cpp"
    "$WORKDIR/src/hash.h"
    "$WORKDIR/src/init.cpp"
    "$WORKDIR/src/init.h"
    "$WORKDIR/src/kernel.cpp"
    "$WORKDIR/src/kernel.h"
    "$WORKDIR/src/key.cpp"
    "$WORKDIR/src/key.h"
    "$WORKDIR/src/keystore.cpp"
    "$WORKDIR/src/keystore.h"
    "$WORKDIR/src/main.cpp"
    "$WORKDIR/src/main.h"
    "$WORKDIR/src/miner.cpp"
    "$WORKDIR/src/miner.h"
    "$WORKDIR/src/mruset.h"
    "$WORKDIR/src/net.cpp"
    "$WORKDIR/src/net.h"
    "$WORKDIR/src/netbase.cpp"
    "$WORKDIR/src/netbase.h"
    "$WORKDIR/src/noui.cpp"
    "$WORKDIR/src/pbkdf2.cpp"
    "$WORKDIR/src/pbkdf2.h"
    "$WORKDIR/src/protocol.cpp"
    "$WORKDIR/src/protocol.h"
    "$WORKDIR/src/rpcblockchain.cpp"
    "$WORKDIR/src/rpcdump.cpp"
    "$WORKDIR/src/rpcmining.cpp"
    "$WORKDIR/src/rpcnet.cpp"
    "$WORKDIR/src/rpcnet1.cpp"
    "$WORKDIR/src/rpcrawtransaction.cpp"
    "$WORKDIR/src/rpcwallet.cpp"
    "$WORKDIR/src/script.cpp"
    "$WORKDIR/src/script.h"
    "$WORKDIR/src/scrypt.cpp"
    "$WORKDIR/src/scrypt.h"
    "$WORKDIR/src/serialize.h"
    "$WORKDIR/src/sync.cpp"
    "$WORKDIR/src/sync.h"
    "$WORKDIR/src/threadsafety.h"
    "$WORKDIR/src/txdb-leveldb.cpp"
    "$WORKDIR/src/txdb-leveldb.h"
    "$WORKDIR/src/txdb.h"
    "$WORKDIR/src/ui_interface.h"
    "$WORKDIR/src/uint256.h"
    "$WORKDIR/src/util.cpp"
    "$WORKDIR/src/util.h"
    "$WORKDIR/src/version.cpp"
    "$WORKDIR/src/version.h"
    "$WORKDIR/src/wallet.cpp"
    "$WORKDIR/src/wallet.h"
    "$WORKDIR/src/walletdb.cpp"
    "$WORKDIR/src/walletdb.h"
    "$WORKDIR/src/json/json_spirit.h"
    "$WORKDIR/src/json/json_spirit_error_position.h"
    "$WORKDIR/src/json/json_spirit_reader.cpp"
    "$WORKDIR/src/json/json_spirit_reader.h"
    "$WORKDIR/src/json/json_spirit_reader_template.h"
    "$WORKDIR/src/json/json_spirit_stream_reader.h"
    "$WORKDIR/src/json/json_spirit_utils.h"
    "$WORKDIR/src/json/json_spirit_value.cpp"
    "$WORKDIR/src/json/json_spirit_value.h"
    "$WORKDIR/src/json/json_spirit_writer.cpp"
    "$WORKDIR/src/json/json_spirit_writer.h"
    "$WORKDIR/src/json/json_spirit_writer_template.h"
    "$WORKDIR/src/leveldb/db/builder.h"
    "$WORKDIR/src/leveldb/db/db_impl.h"
    "$WORKDIR/src/leveldb/db/db_iter.h"
    "$WORKDIR/src/leveldb/db/dbformat.h"
    "$WORKDIR/src/leveldb/db/filename.h"
    "$WORKDIR/src/leveldb/db/log_format.h"
    "$WORKDIR/src/leveldb/db/log_reader.h"
    "$WORKDIR/src/leveldb/db/log_writer.h"
    "$WORKDIR/src/leveldb/db/memtable.h"
    "$WORKDIR/src/leveldb/db/skiplist.h"
    "$WORKDIR/src/leveldb/db/snapshot.h"
    "$WORKDIR/src/leveldb/db/table_cache.h"
    "$WORKDIR/src/leveldb/db/version_edit.h"
    "$WORKDIR/src/leveldb/db/version_set.h"
    "$WORKDIR/src/leveldb/db/write_batch_internal.h"
    "$WORKDIR/src/leveldb/helpers/memenv/memenv.h"
    "$WORKDIR/src/leveldb/include/leveldb/c.h"
    "$WORKDIR/src/leveldb/include/leveldb/cache.h"
    "$WORKDIR/src/leveldb/include/leveldb/comparator.h"
    "$WORKDIR/src/leveldb/include/leveldb/db.h"
    "$WORKDIR/src/leveldb/include/leveldb/env.h"
    "$WORKDIR/src/leveldb/include/leveldb/filter_policy.h"
    "$WORKDIR/src/leveldb/include/leveldb/iterator.h"
    "$WORKDIR/src/leveldb/include/leveldb/options.h"
    "$WORKDIR/src/leveldb/include/leveldb/slice.h"
    "$WORKDIR/src/leveldb/include/leveldb/status.h"
    "$WORKDIR/src/leveldb/include/leveldb/table.h"
    "$WORKDIR/src/leveldb/include/leveldb/table_builder.h"
    "$WORKDIR/src/leveldb/include/leveldb/write_batch.h"
    "$WORKDIR/src/leveldb/port/atomic_pointer.h"
    "$WORKDIR/src/leveldb/port/port.h"
    "$WORKDIR/src/leveldb/port/port_example.h"
    "$WORKDIR/src/leveldb/port/port_posix.h"
    "$WORKDIR/src/leveldb/port/port_win.h"
    "$WORKDIR/src/leveldb/port/thread_annotations.h"
    "$WORKDIR/src/leveldb/port/win/stdint.h"
    "$WORKDIR/src/leveldb/table/block.h"
    "$WORKDIR/src/leveldb/table/block_builder.h"
    "$WORKDIR/src/leveldb/table/filter_block.h"
    "$WORKDIR/src/leveldb/table/format.h"
    "$WORKDIR/src/leveldb/table/iterator_wrapper.h"
    "$WORKDIR/src/leveldb/table/merger.h"
    "$WORKDIR/src/leveldb/table/two_level_iterator.h"
    "$WORKDIR/src/leveldb/util/arena.h"
    "$WORKDIR/src/leveldb/util/coding.h"
    "$WORKDIR/src/leveldb/util/crc32c.h"
    "$WORKDIR/src/leveldb/util/hash.h"
    "$WORKDIR/src/leveldb/util/histogram.h"
    "$WORKDIR/src/leveldb/util/logging.h"
    "$WORKDIR/src/leveldb/util/mutexlock.h"
    "$WORKDIR/src/leveldb/util/posix_logger.h"
    "$WORKDIR/src/leveldb/util/random.h"
    "$WORKDIR/src/leveldb/util/testharness.h"
    "$WORKDIR/src/leveldb/util/testutil.h"
    "$WORKDIR/src/qt/aboutdialog.cpp"
    "$WORKDIR/src/qt/aboutdialog.h"
    "$WORKDIR/src/qt/addressbookpage.cpp"
    "$WORKDIR/src/qt/addressbookpage.h"
    "$WORKDIR/src/qt/addresstablemodel.cpp"
    "$WORKDIR/src/qt/addresstablemodel.h"
    "$WORKDIR/src/qt/askpassphrasedialog.cpp"
    "$WORKDIR/src/qt/askpassphrasedialog.h"
    "$WORKDIR/src/qt/bitcoin.cpp"
    "$WORKDIR/src/qt/bitcoinaddressvalidator.cpp"
    "$WORKDIR/src/qt/bitcoinaddressvalidator.h"
    "$WORKDIR/src/qt/bitcoinamountfield.cpp"
    "$WORKDIR/src/qt/bitcoinamountfield.h"
    "$WORKDIR/src/qt/bitcoingui.cpp"
    "$WORKDIR/src/qt/bitcoingui.h"
    "$WORKDIR/src/qt/bitcoinstrings.cpp"
    "$WORKDIR/src/qt/bitcoinunits.cpp"
    "$WORKDIR/src/qt/bitcoinunits.h"
    "$WORKDIR/src/qt/calcdialog.cpp"
    "$WORKDIR/src/qt/calcdialog.h"
    "$WORKDIR/src/qt/charitydialog.cpp"
    "$WORKDIR/src/qt/charitydialog.h"
    "$WORKDIR/src/qt/clientmodel.cpp"
    "$WORKDIR/src/qt/clientmodel.h"
    "$WORKDIR/src/qt/coincontroldialog.cpp"
    "$WORKDIR/src/qt/coincontroldialog.h"
    "$WORKDIR/src/qt/coincontroltreewidget.cpp"
    "$WORKDIR/src/qt/coincontroltreewidget.h"
    "$WORKDIR/src/qt/csvmodelwriter.cpp"
    "$WORKDIR/src/qt/csvmodelwriter.h"
    "$WORKDIR/src/qt/editaddressdialog.cpp"
    "$WORKDIR/src/qt/editaddressdialog.h"
    "$WORKDIR/src/qt/guiconstants.h"
    "$WORKDIR/src/qt/guiutil.cpp"
    "$WORKDIR/src/qt/guiutil.h"
    "$WORKDIR/src/qt/intro.cpp"
    "$WORKDIR/src/qt/intro.h"
    "$WORKDIR/src/qt/macdockiconhandler.h"
    "$WORKDIR/src/qt/macnotificationhandler.h"
    "$WORKDIR/src/qt/miningpage.cpp"
    "$WORKDIR/src/qt/miningpage.h"
    "$WORKDIR/src/qt/monitoreddatamapper.cpp"
    "$WORKDIR/src/qt/monitoreddatamapper.h"
    "$WORKDIR/src/qt/networkpage.cpp"
    "$WORKDIR/src/qt/networkpage.h"
    "$WORKDIR/src/qt/notificator.cpp"
    "$WORKDIR/src/qt/notificator.h"
    "$WORKDIR/src/qt/optionsdialog.cpp"
    "$WORKDIR/src/qt/optionsdialog.h"
    "$WORKDIR/src/qt/optionsmodel.cpp"
    "$WORKDIR/src/qt/optionsmodel.h"
    "$WORKDIR/src/qt/overviewpage.cpp"
    "$WORKDIR/src/qt/overviewpage.h"
    "$WORKDIR/src/qt/qcustomplot.cpp"
    "$WORKDIR/src/qt/qcustomplot.h"
    "$WORKDIR/src/qt/qrcodedialog.cpp"
    "$WORKDIR/src/qt/qrcodedialog.h"
    "$WORKDIR/src/qt/qtipcserver.cpp"
    "$WORKDIR/src/qt/qtipcserver.h"
    "$WORKDIR/src/qt/qvalidatedlineedit.cpp"
    "$WORKDIR/src/qt/qvalidatedlineedit.h"
    "$WORKDIR/src/qt/qvaluecombobox.cpp"
    "$WORKDIR/src/qt/qvaluecombobox.h"
    "$WORKDIR/src/qt/rpcconsole.cpp"
    "$WORKDIR/src/qt/rpcconsole.h"
    "$WORKDIR/src/qt/sendcoinsdialog.cpp"
    "$WORKDIR/src/qt/sendcoinsdialog.h"
    "$WORKDIR/src/qt/sendcoinsentry.cpp"
    "$WORKDIR/src/qt/sendcoinsentry.h"
    "$WORKDIR/src/qt/shoppingpage.cpp"
    "$WORKDIR/src/qt/shoppingpage.h"
    "$WORKDIR/src/qt/signverifymessagedialog.cpp"
    "$WORKDIR/src/qt/signverifymessagedialog.h"
    "$WORKDIR/src/qt/stakereportdialoge.cpp"
    "$WORKDIR/src/qt/stakereportdialoge.h"
    "$WORKDIR/src/qt/transactiondesc.cpp"
    "$WORKDIR/src/qt/transactiondesc.h"
    "$WORKDIR/src/qt/transactiondescdialog.cpp"
    "$WORKDIR/src/qt/transactiondescdialog.h"
    "$WORKDIR/src/qt/transactionfilterproxy.cpp"
    "$WORKDIR/src/qt/transactionfilterproxy.h"
    "$WORKDIR/src/qt/transactionrecord.cpp"
    "$WORKDIR/src/qt/transactionrecord.h"
    "$WORKDIR/src/qt/transactiontablemodel.cpp"
    "$WORKDIR/src/qt/transactiontablemodel.h"
    "$WORKDIR/src/qt/transactionview.cpp"
    "$WORKDIR/src/qt/transactionview.h"
    "$WORKDIR/src/qt/walletmodel.cpp"
    "$WORKDIR/src/qt/walletmodel.h"
    "$WORKDIR/src/qt/test/test_main.cpp"
    "$WORKDIR/src/qt/test/uritests.cpp"
    "$WORKDIR/src/qt/test/uritests.h"
    "$WORKDIR/src/test/Checkpoints_tests.cpp"
    "$WORKDIR/src/test/DoS_tests.cpp"
    "$WORKDIR/src/test/allocator_tests.cpp"
    "$WORKDIR/src/test/base32_tests.cpp"
    "$WORKDIR/src/test/base58_tests.cpp"
    "$WORKDIR/src/test/base64_tests.cpp"
    "$WORKDIR/src/test/bignum_tests.cpp"
    "$WORKDIR/src/test/getarg_tests.cpp"
    "$WORKDIR/src/test/hmac_tests.cpp"
    "$WORKDIR/src/test/key_tests.cpp"
    "$WORKDIR/src/test/miner_tests.cpp"
    "$WORKDIR/src/test/mruset_tests.cpp"
    "$WORKDIR/src/test/multisig_tests.cpp"
    "$WORKDIR/src/test/netbase_tests.cpp"
    "$WORKDIR/src/test/rpc_tests.cpp"
    "$WORKDIR/src/test/script_P2SH_tests.cpp"
    "$WORKDIR/src/test/script_tests.cpp"
    "$WORKDIR/src/test/serialize_tests.cpp"
    "$WORKDIR/src/test/sigopcount_tests.cpp"
    "$WORKDIR/src/test/test_bitcoin.cpp"
    "$WORKDIR/src/test/transaction_tests.cpp"
    "$WORKDIR/src/test/uint160_tests.cpp"
    "$WORKDIR/src/test/uint256_tests.cpp"
    "$WORKDIR/src/test/util_tests.cpp"
    "$WORKDIR/src/test/wallet_tests.cpp"
    "$WORKDIR/src/zerocoin/Accumulator.cpp"
    "$WORKDIR/src/zerocoin/Accumulator.h"
    "$WORKDIR/src/zerocoin/AccumulatorProofOfKnowledge.cpp"
    "$WORKDIR/src/zerocoin/AccumulatorProofOfKnowledge.h"
    "$WORKDIR/src/zerocoin/Coin.cpp"
    "$WORKDIR/src/zerocoin/Coin.h"
    "$WORKDIR/src/zerocoin/CoinSpend.cpp"
    "$WORKDIR/src/zerocoin/CoinSpend.h"
    "$WORKDIR/src/zerocoin/Commitment.cpp"
    "$WORKDIR/src/zerocoin/Commitment.h"
    "$WORKDIR/src/zerocoin/ParamGeneration.cpp"
    "$WORKDIR/src/zerocoin/ParamGeneration.h"
    "$WORKDIR/src/zerocoin/Params.cpp"
    "$WORKDIR/src/zerocoin/Params.h"
    "$WORKDIR/src/zerocoin/SerialNumberSignatureOfKnowledge.cpp"
    "$WORKDIR/src/zerocoin/SerialNumberSignatureOfKnowledge.h"
    "$WORKDIR/src/zerocoin/SpendMetaData.cpp"
    "$WORKDIR/src/zerocoin/SpendMetaData.h"
    "$WORKDIR/src/zerocoin/ZeroTest.cpp"
    "$WORKDIR/src/zerocoin/ZeroTest.h"
    "$WORKDIR/src/zerocoin/Zerocoin.h"

)

# Backup original files
for file in "${FILES_TO_UPDATE[@]}"; do
    cp $file $file.bak
done

# Replace Boost libraries with C++17 features
for file in "${FILES_TO_UPDATE[@]}"; do
    # Replace boost::thread with std::thread
    sed -i 's/#include <boost\/thread\.hpp>/#include <thread>/g' $file
    sed -i 's/boost::thread/std::thread/g' $file
    
    # Replace boost::filesystem with std::filesystem
    sed -i 's/#include <boost\/filesystem\.hpp>/#include <filesystem>/g' $file
    sed -i 's/boost::filesystem/std::filesystem/g' $file
    
    # Replace boost::regex with std::regex
    sed -i 's/#include <boost\/regex\.hpp>/#include <regex>/g' $file
    sed -i 's/boost::regex/std::regex/g' $file

    # Replace boost::bind with std::bind or lambdas
    sed -i 's/boost::bind/std::bind/g' $file
done

echo "Boost dependencies have been replaced with C++17 features in all .cpp and .h files."
